name: Building
# on: [push] # se va a ejecutar cuando se haga un push
on: # en vez de hacer el if, con esto es que se ejecuta solo cuando haya una etiqueta con un tag que empiece con v
  push:
    tags:
      - "v*.*.*"

jobs:
  building: # nombre de la ejec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # descargo un repositorio con este comando existente @v3 es la version de la accion
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1.3.1
      - run: poetry build
      # - run: ls ${{ github.workspace }} # para ver si esta el build creado
      - name: Publish to GH Releases
        uses: softprops/action-gh-release@v1
        with: # para usar parametros se usa esta linea
          files:  ${{ github.workspace }}/dist/* #|  la barra vertical para enumerar varias cosas
