name: Building
on: [push]
# on:
  # push:
  #   tags:
  #     - "v*"

jobs:
  building: # nombre de la ejec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # descargo un repositorio con este comando existente @v3 es la version de la accion
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1.3.1
      - name: Install dependecy
        run: poetry install
      - name: Testing
        run: poetry run pytest --junitxml=jest-junit.xml
        uses: dorny/test-reporter@v1
      - run: poetry build
      # - run: ls ${{ github.workspace }} # para ver si esta el build creado
      if: startsWith(github.ref, 'refs/tags/v')
        - name: Publish to GH Releases
          uses: softprops/action-gh-release@v1
          with: # para usar parametros se usa esta linea
            files:  ${{ github.workspace }}/dist/* #|  la barra vertical para enumerar varias cosas
